//  Copyright (C) 2026 jhhr and contributors
//  SPDX-License-Identifier: GPL-3.0-or-later

using System.Globalization;
using System.Text;
using SubsRetimer.Core;

namespace SubsRetimer.Tests
{
  /// <summary>Synthetic subtitle files. No third-party subtitle content is used.</summary>
  internal static class Fixtures
  {
    public const string AssHeader =
      "[Script Info]\n; Script generated by test\nScriptType: v4.00+\nPlayResX: 1280\nPlayResY: 720\n\n" +
      "[V4+ Styles]\nFormat: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\n" +
      "Style: Default,Arial,48,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,0,2,10,10,10,1\n\n" +
      "[Events]\nFormat: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n";

    public static string AssDialogue(TimeSpan s, TimeSpan e, string text, string style = "Default", string actor = "") =>
      $"Dialogue: 0,{TimeFormat.FormatAss(s)},{TimeFormat.FormatAss(e)},{style},{actor},0,0,0,,{text}";

    public static string SrtCue(int n, TimeSpan s, TimeSpan e, string text) =>
      $"{n}\n{TimeFormat.FormatSrt(s)} --> {TimeFormat.FormatSrt(e)}\n{text}\n";

    public static TimeSpan Ms(double ms) => TimeSpan.FromMilliseconds(ms);

    /// <summary>Lines every ~2.5 s with 1.8 s duration, for <paramref name="count"/> lines starting at <paramref name="startMs"/>.</summary>
    public static List<RetimerLine> Lines(int count, double startMs = 1000, double stepMs = 2500, double durMs = 1800)
    {
      var list = new List<RetimerLine>();
      for (int i = 0; i < count; i++)
        list.Add(new RetimerLine
        {
          Start = Ms(startMs + i * stepMs),
          End = Ms(startMs + i * stepMs + durMs),
          Text = "line " + (i + 1).ToString(CultureInfo.InvariantCulture),
          RawIndex = i
        });
      return list;
    }

    /// <summary>
    /// Irregular dialogue timings (seeded): gaps of 0.2-4 s and durations of
    /// 0.6-3 s, like real speech. Periodic timings would make offsets that are
    /// multiples of the period indistinguishable.
    /// </summary>
    public static List<RetimerLine> Dialogue(int count, int seed = 1, double startMs = 800)
    {
      var rnd = new Random(seed);
      var list = new List<RetimerLine>();
      double t = startMs;
      for (int i = 0; i < count; i++)
      {
        double dur = 600 + rnd.Next(0, 2400);
        list.Add(new RetimerLine
        {
          Start = Ms(t),
          End = Ms(t + dur),
          Text = "line " + (i + 1).ToString(CultureInfo.InvariantCulture),
          RawIndex = i
        });
        t += dur + 200 + rnd.Next(0, 3800);
      }
      return list;
    }

    public static string TempPath(string ext)
    {
      string dir = Path.Combine(Path.GetTempPath(), "subsretimer-tests", Guid.NewGuid().ToString("N"));
      Directory.CreateDirectory(dir);
      return Path.Combine(dir, "sub" + ext);
    }

    public static string WriteTemp(string ext, string content, Encoding? enc = null, bool bom = false)
    {
      string path = TempPath(ext);
      enc ??= new UTF8Encoding(bom);
      using var fs = File.Create(path);
      if (bom) fs.Write(enc.GetPreamble());
      fs.Write(enc.GetBytes(content));
      return path;
    }

    public static string AssFile(IEnumerable<RetimerLine> lines, string newLine = "\n")
    {
      var sb = new StringBuilder(AssHeader.Replace("\n", newLine));
      foreach (var l in lines) sb.Append(AssDialogue(l.Start, l.End, l.Text)).Append(newLine);
      return sb.ToString();
    }

    public static string SrtFile(IEnumerable<RetimerLine> lines, string newLine = "\n")
    {
      var sb = new StringBuilder();
      int n = 1;
      foreach (var l in lines) sb.Append(SrtCue(n++, l.Start, l.End, l.Text).Replace("\n", newLine)).Append(newLine);
      return sb.ToString();
    }
  }
}
